# Generated by Django 4.1.6 on 2023-05-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_comment_sentiment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLike', models.BooleanField()),
                ('idPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postverifie')),
                ('idcit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
    ]
