# Generated by Django 4.1.6 on 2023-05-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postverifie',
            name='sentiment',
        ),
    ]
